import type { NormalizedRecord } from '@/types';

// Reference date: today is 2026-09-26. We compute relative dates.
function daysAgo(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString().split('T')[0];
}

function daysFromNow(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
}

export const demoRecords: NormalizedRecord[] = [
  // === OVERDUE INVOICES ===
  {
    id: 'demo-1',
    customer: 'ABC Construction Ltd',
    phone: '+233 24 123 4567',
    email: 'accounts@abcconstruction.gh',
    reference: 'INV-1042',
    recordType: 'invoice',
    amount: 12000,
    date: daysAgo(54),
    dueDate: daysAgo(24),
    status: 'Unpaid',
    lastContact: daysAgo(24),
    rawRow: {},
  },
  {
    id: 'demo-2',
    customer: 'Prime Estates',
    phone: '+233 20 987 6543',
    email: 'finance@primeestates.gh',
    reference: 'INV-1038',
    recordType: 'invoice',
    amount: 6500,
    date: daysAgo(40),
    dueDate: daysAgo(10),
    status: 'Unpaid',
    lastContact: daysAgo(10),
    rawRow: {},
  },
  {
    id: 'demo-3',
    customer: 'Kente Foods Ltd',
    phone: '+233 27 555 0199',
    email: 'ap@kentefoods.gh',
    reference: 'INV-1035',
    recordType: 'invoice',
    amount: 18500,
    date: daysAgo(70),
    dueDate: daysAgo(40),
    status: 'Pending',
    lastContact: daysAgo(35),
    rawRow: {},
  },
  // === DUE SOON ===
  {
    id: 'demo-4',
    customer: 'Bright Office Supplies',
    phone: '+233 24 444 1122',
    email: 'payments@brightoffice.gh',
    reference: 'INV-1051',
    recordType: 'invoice',
    amount: 3400,
    date: daysAgo(23),
    dueDate: daysFromNow(3),
    status: 'Sent',
    lastContact: daysAgo(7),
    rawRow: {},
  },
  {
    id: 'demo-5',
    customer: 'Metro Engineering',
    phone: '+233 20 777 8899',
    email: 'accounts@metroeng.gh',
    reference: 'INV-1053',
    recordType: 'invoice',
    amount: 9200,
    date: daysAgo(20),
    dueDate: daysFromNow(5),
    status: 'Unpaid',
    lastContact: daysAgo(5),
    rawRow: {},
  },
  // === PAID / HEALTHY ===
  {
    id: 'demo-6',
    customer: 'Golden Homes',
    phone: '+233 27 333 4455',
    email: 'finance@goldenhomes.gh',
    reference: 'INV-1048',
    recordType: 'invoice',
    amount: 7800,
    date: daysAgo(15),
    dueDate: daysAgo(2),
    status: 'Paid',
    lastContact: daysAgo(2),
    rawRow: {},
  },
  {
    id: 'demo-7',
    customer: 'Nana Trading Co.',
    phone: '+233 24 222 3344',
    email: 'info@nanatrading.gh',
    reference: 'INV-1045',
    recordType: 'invoice',
    amount: 5200,
    date: daysAgo(30),
    dueDate: daysAgo(5),
    status: 'Paid',
    lastContact: daysAgo(3),
    rawRow: {},
  },
  // === QUOTATIONS AWAITING RESPONSE ===
  {
    id: 'demo-8',
    customer: 'Accra Digital Services',
    phone: '+233 55 111 2233',
    email: 'procurement@accradigital.gh',
    reference: 'QT-220',
    recordType: 'quotation',
    amount: 8000,
    date: daysAgo(9),
    dueDate: null,
    status: 'Awaiting Response',
    lastContact: daysAgo(9),
    rawRow: {},
  },
  {
    id: 'demo-9',
    customer: 'ABC Construction Ltd',
    phone: '+233 24 123 4567',
    email: 'info@abcconstruction.gh',
    reference: 'QT-225',
    recordType: 'quotation',
    amount: 15000,
    date: daysAgo(14),
    dueDate: null,
    status: 'Sent',
    lastContact: daysAgo(14),
    rawRow: {},
  },
  {
    id: 'demo-10',
    customer: 'Prime Estates',
    phone: '+233 20 987 6543',
    email: 'projects@primeestates.gh',
    reference: 'QT-228',
    recordType: 'quotation',
    amount: 22000,
    date: daysAgo(18),
    dueDate: null,
    status: 'Open',
    lastContact: daysAgo(18),
    rawRow: {},
  },
  {
    id: 'demo-11',
    customer: 'Kente Foods Ltd',
    phone: '+233 27 555 0199',
    email: 'purchasing@kentefoods.gh',
    reference: 'QT-231',
    recordType: 'quotation',
    amount: 5600,
    date: daysAgo(7),
    dueDate: null,
    status: 'Sent',
    lastContact: daysAgo(7),
    rawRow: {},
  },
  {
    id: 'demo-12',
    customer: 'Golden Homes',
    phone: '+233 27 333 4455',
    email: 'projects@goldenhomes.gh',
    reference: 'QT-235',
    recordType: 'quotation',
    amount: 12000,
    date: daysAgo(12),
    dueDate: null,
    status: 'Pending',
    lastContact: daysAgo(12),
    rawRow: {},
  },
  // === RECENT QUOTATIONS (healthy) ===
  {
    id: 'demo-13',
    customer: 'Metro Engineering',
    phone: '+233 20 777 8899',
    email: 'info@metroeng.gh',
    reference: 'QT-240',
    recordType: 'quotation',
    amount: 9800,
    date: daysAgo(2),
    dueDate: null,
    status: 'Sent',
    lastContact: daysAgo(2),
    rawRow: {},
  },
  {
    id: 'demo-14',
    customer: 'Bright Office Supplies',
    phone: '+233 24 444 1122',
    email: 'orders@brightoffice.gh',
    reference: 'QT-242',
    recordType: 'quotation',
    amount: 3200,
    date: daysAgo(1),
    dueDate: null,
    status: 'Sent',
    lastContact: daysAgo(1),
    rawRow: {},
  },
  // === CLOSED QUOTATIONS ===
  {
    id: 'demo-15',
    customer: 'Nana Trading Co.',
    phone: '+233 24 222 3344',
    email: 'info@nanatrading.gh',
    reference: 'QT-210',
    recordType: 'quotation',
    amount: 4500,
    date: daysAgo(45),
    dueDate: null,
    status: 'Closed',
    lastContact: daysAgo(40),
    rawRow: {},
  },
  // === INACTIVE CUSTOMERS ===
  {
    id: 'demo-16',
    customer: 'Accra Digital Services',
    phone: '+233 55 111 2233',
    email: 'info@accradigital.gh',
    reference: '',
    recordType: 'customer',
    amount: null,
    date: daysAgo(65),
    dueDate: null,
    status: '',
    lastContact: daysAgo(65),
    rawRow: {},
  },
  {
    id: 'demo-17',
    customer: 'Nana Trading Co.',
    phone: '+233 24 222 3344',
    email: 'info@nanatrading.gh',
    reference: '',
    recordType: 'customer',
    amount: null,
    date: daysAgo(48),
    dueDate: null,
    status: '',
    lastContact: daysAgo(48),
    rawRow: {},
  },
  {
    id: 'demo-18',
    customer: 'Golden Homes',
    phone: '+233 27 333 4455',
    email: 'info@goldenhomes.gh',
    reference: '',
    recordType: 'customer',
    amount: null,
    date: daysAgo(35),
    dueDate: null,
    status: '',
    lastContact: daysAgo(35),
    rawRow: {},
  },
  // === ACTIVE CUSTOMERS (healthy) ===
  {
    id: 'demo-19',
    customer: 'Metro Engineering',
    phone: '+233 20 777 8899',
    email: 'info@metroeng.gh',
    reference: '',
    recordType: 'customer',
    amount: null,
    date: daysAgo(5),
    dueDate: null,
    status: '',
    lastContact: daysAgo(5),
    rawRow: {},
  },
  {
    id: 'demo-20',
    customer: 'Bright Office Supplies',
    phone: '+233 24 444 1122',
    email: 'info@brightoffice.gh',
    reference: '',
    recordType: 'customer',
    amount: null,
    date: daysAgo(8),
    dueDate: null,
    status: '',
    lastContact: daysAgo(8),
    rawRow: {},
  },
  // === MISSING DATA ===
  {
    id: 'demo-21',
    customer: '',
    phone: '+233 26 000 0001',
    email: 'unknown@company.gh',
    reference: 'INV-1060',
    recordType: 'invoice',
    amount: null,
    date: daysAgo(10),
    dueDate: null,
    status: '',
    lastContact: null,
    rawRow: {},
  },
  {
    id: 'demo-22',
    customer: 'Prime Estates',
    phone: '',
    email: '',
    reference: 'QT-250',
    recordType: 'quotation',
    amount: null,
    date: daysAgo(6),
    dueDate: null,
    status: '',
    lastContact: null,
    rawRow: {},
  },
  // === MORE OVERDUE ===
  {
    id: 'demo-23',
    customer: 'Kente Foods Ltd',
    phone: '+233 27 555 0199',
    email: 'ap@kentefoods.gh',
    reference: 'INV-1030',
    recordType: 'invoice',
    amount: 4200,
    date: daysAgo(55),
    dueDate: daysAgo(25),
    status: 'Unpaid',
    lastContact: daysAgo(20),
    rawRow: {},
  },
  {
    id: 'demo-24',
    customer: 'Accra Digital Services',
    phone: '+233 55 111 2233',
    email: 'finance@accradigital.gh',
    reference: 'INV-1055',
    recordType: 'invoice',
    amount: 6800,
    date: daysAgo(35),
    dueDate: daysAgo(5),
    status: 'Pending',
    lastContact: daysAgo(5),
    rawRow: {},
  },
  // === COMPLETED ===
  {
    id: 'demo-25',
    customer: 'Metro Engineering',
    phone: '+233 20 777 8899',
    email: 'accounts@metroeng.gh',
    reference: 'INV-1040',
    recordType: 'invoice',
    amount: 11000,
    date: daysAgo(50),
    dueDate: daysAgo(20),
    status: 'Completed',
    lastContact: daysAgo(18),
    rawRow: {},
  },
];
